/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.DocExcel;
import BUS.QuanLyLoaiSanPhamBUS;
import BUS.QuanLyNhaXuatBanBUS;
import BUS.QuanLySanPhamBUS;
import BUS.QuanLyTacGiaBUS;
import BUS.XuatExcel;
import DTO.SanPham;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dangk
 */
public class SanPhamPanel extends javax.swing.JPanel {
    private DefaultTableModel mdtb1;
    private QuanLySanPhamBUS qlspBUS = new QuanLySanPhamBUS();
    private QuanLyLoaiSanPhamBUS qllspBUS = new QuanLyLoaiSanPhamBUS();
    private QuanLyTacGiaBUS qltgBUS = new QuanLyTacGiaBUS();
    private QuanLyNhaXuatBanBUS qlnxbBUS = new QuanLyNhaXuatBanBUS();

    /**
     * Creates new form SanPhamPanel
     */
    public SanPhamPanel() {
        initComponents();
        mdtb1 = (DefaultTableModel) tbSanPham.getModel();
        setDataToTable(qlspBUS.getDssp());
        
        
        tbSanPham.addMouseListener(new MouseAdapter() {
            public void mouseReleased(MouseEvent me) {
                String masp =(String) tbSanPham.getValueAt(tbSanPham.getSelectedRow(), 1);
                showInfo(masp);
            }
        });
        
        
        addDocumentListener(tfTim);
        addDocumentListener(tfGia1);
        addDocumentListener(tfGia2);
        addDocumentListener(tfSoLuong1);
        addDocumentListener(tfSoLuong2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXuatExcel = new javax.swing.JButton();
        btnNhapExcel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cbTypeSearch = new javax.swing.JComboBox<>();
        tfTim = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        tfSoLuong2 = new javax.swing.JTextField();
        tfSoLuong1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        tfGia2 = new javax.swing.JTextField();
        tfGia1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        tfMaSP = new javax.swing.JTextField();
        tfLoaiSP = new javax.swing.JTextField();
        tfTenSP = new javax.swing.JTextField();
        tfDonGia = new javax.swing.JTextField();
        tfSoLuong = new javax.swing.JTextField();
        tfTG = new javax.swing.JTextField();
        tfNXB = new javax.swing.JTextField();
        spSanPham = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1110, 800));
        setPreferredSize(new java.awt.Dimension(1110, 800));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(46, 134, 222));
        jPanel2.setPreferredSize(new java.awt.Dimension(1120, 55));

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setForeground(new java.awt.Color(0, 255, 0));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8-add-property-30.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setFocusable(false);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel2.add(btnThem);

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setForeground(new java.awt.Color(255, 0, 0));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8-delete-bin-30.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setFocusable(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa);

        btnSua.setBackground(new java.awt.Color(255, 255, 255));
        btnSua.setForeground(new java.awt.Color(0, 0, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8-support-30.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setFocusable(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSua);

        btnXuatExcel.setBackground(new java.awt.Color(255, 255, 255));
        btnXuatExcel.setForeground(new java.awt.Color(0, 255, 0));
        btnXuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8-microsoft-excel-30.png"))); // NOI18N
        btnXuatExcel.setText("Xuất Excel");
        btnXuatExcel.setFocusable(false);
        btnXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelActionPerformed(evt);
            }
        });
        jPanel2.add(btnXuatExcel);

        btnNhapExcel.setBackground(new java.awt.Color(255, 255, 255));
        btnNhapExcel.setForeground(new java.awt.Color(0, 255, 0));
        btnNhapExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8-microsoft-excel-30.png"))); // NOI18N
        btnNhapExcel.setText("Nhập Excel");
        btnNhapExcel.setFocusable(false);
        btnNhapExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapExcelActionPerformed(evt);
            }
        });
        jPanel2.add(btnNhapExcel);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(1249, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tìm kiếm"));
        jPanel4.setPreferredSize(new java.awt.Dimension(280, 70));
        jPanel4.setLayout(null);

        cbTypeSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã sản phẩm", "Mã loại", "Tên", "Đơn giá (nghìn)", "Số lượng", "Mã tác giả", "Mã nhà xuất bản" }));
        cbTypeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypeSearchActionPerformed(evt);
            }
        });
        jPanel4.add(cbTypeSearch);
        cbTypeSearch.setBounds(20, 30, 100, 20);

        tfTim.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tất cả"));
        tfTim.setPreferredSize(new java.awt.Dimension(130, 36));
        jPanel4.add(tfTim);
        tfTim.setBounds(130, 20, 140, 36);

        jPanel3.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Số lượng"));
        jPanel5.setPreferredSize(new java.awt.Dimension(150, 70));
        jPanel5.setLayout(null);

        tfSoLuong2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tới"));
        tfSoLuong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoLuong2ActionPerformed(evt);
            }
        });
        jPanel5.add(tfSoLuong2);
        tfSoLuong2.setBounds(80, 20, 50, 36);

        tfSoLuong1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Từ"));
        jPanel5.add(tfSoLuong1);
        tfSoLuong1.setBounds(20, 20, 50, 36);

        jPanel3.add(jPanel5);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Đơn giá"));
        jPanel7.setPreferredSize(new java.awt.Dimension(150, 70));
        jPanel7.setLayout(null);

        tfGia2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tới"));
        tfGia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGia2ActionPerformed(evt);
            }
        });
        jPanel7.add(tfGia2);
        tfGia2.setBounds(80, 20, 50, 36);

        tfGia1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Từ"));
        jPanel7.add(tfGia1);
        tfGia1.setBounds(20, 20, 50, 36);

        jPanel3.add(jPanel7);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel6.setPreferredSize(new java.awt.Dimension(1399, 300));

        lbImage.setAlignmentX(0.5F);
        lbImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbImage.setPreferredSize(new java.awt.Dimension(250, 250));
        jPanel6.add(lbImage);

        jPanel9.setPreferredSize(new java.awt.Dimension(300, 250));

        tfMaSP.setEditable(false);
        tfMaSP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Mã sản phẩm"));
        tfMaSP.setPreferredSize(new java.awt.Dimension(140, 35));
        tfMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaSPActionPerformed(evt);
            }
        });
        jPanel9.add(tfMaSP);

        tfLoaiSP.setEditable(false);
        tfLoaiSP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Loại sản phẩm"));
        tfLoaiSP.setPreferredSize(new java.awt.Dimension(140, 35));
        jPanel9.add(tfLoaiSP);

        tfTenSP.setEditable(false);
        tfTenSP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tên sản phẩm"));
        tfTenSP.setPreferredSize(new java.awt.Dimension(140, 35));
        tfTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenSPActionPerformed(evt);
            }
        });
        jPanel9.add(tfTenSP);

        tfDonGia.setEditable(false);
        tfDonGia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Đơn giá"));
        tfDonGia.setPreferredSize(new java.awt.Dimension(140, 35));
        jPanel9.add(tfDonGia);

        tfSoLuong.setEditable(false);
        tfSoLuong.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Số lượng"));
        tfSoLuong.setPreferredSize(new java.awt.Dimension(100, 35));
        tfSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoLuongActionPerformed(evt);
            }
        });
        jPanel9.add(tfSoLuong);

        tfTG.setEditable(false);
        tfTG.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tác giả"));
        tfTG.setPreferredSize(new java.awt.Dimension(140, 35));
        tfTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTGActionPerformed(evt);
            }
        });
        jPanel9.add(tfTG);

        tfNXB.setEditable(false);
        tfNXB.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nhà xuất bản"));
        tfNXB.setPreferredSize(new java.awt.Dimension(140, 35));
        jPanel9.add(tfNXB);

        jPanel6.add(jPanel9);

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        spSanPham.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spSanPham.setPreferredSize(new java.awt.Dimension(452, 370));

        tbSanPham.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Mã loại ", "Tên", "Đơn giá", "Số lượng", "Hình ảnh", "Mã tác giả", "Mã NXB"
            }
        ));
        tbSanPham.setFillsViewportHeight(true);
        tbSanPham.setRowHeight(40);
        tbSanPham.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tbSanPham.setShowGrid(true);
        spSanPham.setViewportView(tbSanPham);
        if (tbSanPham.getColumnModel().getColumnCount() > 0) {
            tbSanPham.getColumnModel().getColumn(0).setMaxWidth(50);
            tbSanPham.getColumnModel().getColumn(1).setMaxWidth(80);
            tbSanPham.getColumnModel().getColumn(2).setMaxWidth(80);
            tbSanPham.getColumnModel().getColumn(3).setMaxWidth(300);
            tbSanPham.getColumnModel().getColumn(4).setMaxWidth(150);
            tbSanPham.getColumnModel().getColumn(5).setMaxWidth(100);
            tbSanPham.getColumnModel().getColumn(6).setMaxWidth(150);
            tbSanPham.getColumnModel().getColumn(7).setMaxWidth(100);
            tbSanPham.getColumnModel().getColumn(8).setMaxWidth(100);
        }

        jPanel1.add(spSanPham, java.awt.BorderLayout.PAGE_END);
        spSanPham.getVerticalScrollBar().setUnitIncrement(8);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cbTypeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeSearchActionPerformed
        tfTim.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(),cbTypeSearch.getSelectedItem().toString()));
            tfTim.requestFocus();
            if (!tfTim.getText().equals("")) {
                tfSearchOnChange();
            }
    }//GEN-LAST:event_cbTypeSearchActionPerformed

    private void tfSoLuong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoLuong2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoLuong2ActionPerformed

    private void tfGia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGia2ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        ThemSuaSanPhamForm themsp = new ThemSuaSanPhamForm("Thêm", "");
        themsp.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                qlspBUS.readDB();
                setDataToTable(qlspBUS.getDssp()); // refresh
            }
        });
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            String masp =(String) tbSanPham.getValueAt(tbSanPham.getSelectedRow(), 1);
            if (masp != null) {
                ThemSuaSanPhamForm suasp = new ThemSuaSanPhamForm("Sửa", masp);

                // https://stackoverflow.com/questions/4154780/jframe-catch-dispose-event
                suasp.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                        qlspBUS.readDB();
                        setDataToTable(qlspBUS.getDssp()); // refresh
                    }
                });
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Chưa chọn sản phẩm nào để sửa");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            String masp =(String) tbSanPham.getValueAt(tbSanPham.getSelectedRow(), 1);
            if (masp != null) {
                QuanLySanPhamBUS qlspBUS = new QuanLySanPhamBUS();
                if (JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn XÓA HOÀN TOÀN sản phẩm " + masp + " ?", 
                        "Chú ý", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                    qlspBUS.delete(masp);
                    qlspBUS.readDB();
                    setDataToTable(qlspBUS.getDssp()); // refresh
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Chưa chọn sản phẩm nào để xóa");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tfMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaSPActionPerformed

    private void tfTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenSPActionPerformed

    private void tfSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoLuongActionPerformed

    private void tfTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTGActionPerformed

    private void btnXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelActionPerformed
        new XuatExcel().xuatFileExcelSanPham();
    }//GEN-LAST:event_btnXuatExcelActionPerformed

    private void btnNhapExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapExcelActionPerformed
        new DocExcel().docFileExcelSanPham();
    }//GEN-LAST:event_btnNhapExcelActionPerformed
    private void setDataToTable(ArrayList<SanPham> data) {
        mdtb1.setRowCount(0); // xóa table hiện có
        int stt = 1; // lưu số thứ tự dòng hiện tại
        for (SanPham sp : data) {
                mdtb1.addRow(new String[]{
                    String.valueOf(stt),
                    sp.getMaSP(),
                    sp.getMaLSP(),
                    sp.getTenSP(),
                    PriceFormatter.format(sp.getDonGia()),
                    String.valueOf(sp.getSoLuong()),
                    sp.getFileNameHinhAnh(),
                    sp.getMaTG(),
                    sp.getMaNXB()
                });
                stt++;
            }
    }
    
    private void tfSearchOnChange() {
        int soluong1 = -1, soluong2 = -1;
        float gia1 = -1, gia2 = -1;

        try {
            soluong1 = Integer.parseInt(tfSoLuong1.getText());
            tfSoLuong1.setForeground(Color.black);
        } catch (NumberFormatException e) {
            tfSoLuong1.setForeground(Color.red);
        }
        try {
            soluong2 = Integer.parseInt(tfSoLuong2.getText());
            tfSoLuong2.setForeground(Color.black);
        } catch (NumberFormatException e) {
            tfSoLuong2.setForeground(Color.red);
        }
        try {
            gia1 = Float.parseFloat(tfGia1.getText());
            tfGia1.setForeground(Color.black);
        } catch (NumberFormatException e) {
            tfGia1.setForeground(Color.red);
        }
        try {
            gia2 = Float.parseFloat(tfGia2.getText());
            tfGia2.setForeground(Color.black);
        } catch (NumberFormatException e) {
            tfGia2.setForeground(Color.red);
        }

        setDataToTable(qlspBUS.search(tfTim.getText(),
                cbTypeSearch.getSelectedItem().toString(), soluong1, soluong2, gia1, gia2, -1));
    }
        
    private void addDocumentListener(JTextField tf) {
        // https://stackoverflow.com/questions/3953208/value-change-listener-to-jtextfield
        tf.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                tfSearchOnChange();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                tfSearchOnChange();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                tfSearchOnChange();
            }
        });
    }
    
    public void showInfo(String masp) {
        // https://stackoverflow.com/questions/16343098/resize-a-picture-to-fit-a-jlabel
        if (masp != null) {
            // show hình
            for (SanPham sp : qlspBUS.getDssp()) {
                if (sp.getMaSP().equals(masp)) {
                    int w = lbImage.getWidth();
                    int h = lbImage.getHeight();
                    ImageIcon img = new ImageIcon(getClass().getResource("/giaodienchuan/images/Product Images/" + sp.getFileNameHinhAnh()));
                    Image imgScaled = img.getImage().getScaledInstance(w, h, Image.SCALE_DEFAULT);
                    lbImage.setIcon(new ImageIcon(imgScaled));

                    // show info
                    String loai = qllspBUS.getLoaiSanPham(sp.getMaLSP()).getTenLSP();
                    String tg = qltgBUS.getTacGia(sp.getMaTG()).getTenTG();
                    String nxb = qlnxbBUS.getNhaXuatBan(sp.getMaNXB()).getTenNXB();
                    tfMaSP.setText(sp.getMaSP());
                    tfTenSP.setText(sp.getTenSP());
                    tfLoaiSP.setText(loai + " - " + sp.getMaLSP());
                    tfTG.setText(tg + " - " + sp.getMaTG());
                    tfNXB.setText(nxb + " - " + sp.getMaNXB());
                    tfDonGia.setText(PriceFormatter.format(sp.getDonGia()));
                    tfSoLuong.setText(String.valueOf(sp.getSoLuong()));
                    return;
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapExcel;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.JComboBox<String> cbTypeSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbImage;
    private javax.swing.JScrollPane spSanPham;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField tfDonGia;
    private javax.swing.JTextField tfGia1;
    private javax.swing.JTextField tfGia2;
    private javax.swing.JTextField tfLoaiSP;
    private javax.swing.JTextField tfMaSP;
    private javax.swing.JTextField tfNXB;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfSoLuong1;
    private javax.swing.JTextField tfSoLuong2;
    private javax.swing.JTextField tfTG;
    private javax.swing.JTextField tfTenSP;
    private javax.swing.JTextField tfTim;
    // End of variables declaration//GEN-END:variables
}
